### ISSUE TITLE
Recomendaciones de mejora

### ISSUE THREAD

**Issue by gaposx** [HeydyCH/lim-2018-05-bc-core-am-cipher#1]
**README**
* Podrías haber incluído decisiones de diseño (lógica del algoritmo o visual).
* Ten cuidado con la ortografía.

**HTML**
* Te sugerimos usar más etiquetas semánticas como `<header>`, `<section>`, `<footer>`.
* Para seguir buenas prácticas, te sugerimos definir los `id` y `clases` de elementos en minúsculas y separados por guiones (-).
* No olvides validar tu HTML, revisa [esta URL](https://validator.w3.org/nu/?doc=https%3A%2F%2Fheydych.github.io%2Flim-2018-05-bc-core-am-cipher%2Fsrc%2F) para que observes tus errores.

**JS**
* Existen variables que no son necesarias a declarar, y pueden hacer más compacto y legible tu código.
* Recuerda que uno de los requerimientos del proyecto era estar implementado completamente en ES6. Te sugerimos aplicarlo en las definiciones de funciones y loops.
* Para proyectos futuros, te sugerimos seguir la [guía de estilos de Laboratoria sobre JS](https://github.com/Laboratoria/js-style-guide).

**CSS**
* Recuerda usar clases descriptivas y en inglés.
* Te sugerimos no usar tamaños fijos (en px) para los contenedores de tus elementos para que puedan adaptarse a diferentes estilos de pantalla.

**TESTS**
* Debemos eliminar una etiqueta </center> que se dejó en el código HTML para poder correrlos y ver que cubriste el 100%. Ten más cuidado en los siguientes retos.

En general, buen trabajo!

**Comment by MayumyCH** [comment]
Gracias por las recomendaciones  , se te agradece  Gonzalo :) 👍
